spring.application.name=firstspringai
server.port=8081


resilience4j.circuitbreaker.instances.openLibraryService.sliding-window-size=5
resilience4j.circuitbreaker.instances.openLibraryService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.openLibraryService.wait-duration-in-open-state=10s

spring.ai.openai.api-key=API_SECRET
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.temperature=0.7

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

