IN AI/ML, a vector is just an array of numbers that represents some king of information
(text, image, audio, video etc) in a mathematical form.

Translation of Meaning: Machine learning models (like LLMs) cannot process raw text or images directly. 
They translate data into a list of hundreds or thousands of floating-point numbers (e.g., [0.12, -0.45, 0.89, ...]).

 It allows to search by similarity (cosine similarity, euclidean distance etc)

Vector Database (Pinecone, Milvus, Qdrant, pgvector)
data type : Unstructured data (represented as float arrays)
Indexing : Approximate Nearest Neighbor (ANN)
Primary Use : AI chatbots (RAG), semantic search, recommendations


A vector database is a specialized storage system designed to rapidly store, index, and 
query these high-dimensional mathematical representations based on their similarity rather than exact keyword matches.

